CONFIG:
  IMG_SHAPE:
    - 105
    - 105
    - 1
  BATCH_SIZE: 64
  EPOCHS: 100
  LEARNING_RATE: 0.00006
  VALIDATION_SPLIT: 0.1

PATHS:
  BASE_PATH: "data/faces/"
  TEST_CLASSES: "test/classes/"
  TEST_SAMPLES: "test/samples/"
  MODEL_PATH: "model/siamese_model/"
