CONFIG:
  IMG_SHAPE:
    - 105
    - 105
    - 1
  BATCH_SIZE: 128
  EPOCHS: 420
  LEARNING_RATE: 0.0001
  VALIDATION_SPLIT: 0.2

PATHS:
  BASE_PATH: "data/faces/"
  TEST_CLASSES: "test/classes/"
  TEST_SAMPLES: "test/samples/"
  MODEL_PATH: "model/siamese_model/"
