CONFIG:
  IMG_SHAPE:
    - 92
    - 112
    - 1
  BATCH_SIZE: 64
  EPOCHS: 500
  LEARNING_RATE: 0.00005
  VALIDATION_SPLIT: 0.2

PATHS:
  BASE_PATH: "data/faces/"
  TEST_CLASSES: "test/classes/"
  TEST_SAMPLES: "test/samples/"
  MODEL_PATH: "model/siamese_model/"
